# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '17.0.0'

    - name: Install dependencies
      run: |
        brew install cocoapods
        pod install

    - name: Build app
      run: xcodebuild -workspace Pinsoft-WeatherApp.xcworkspace -scheme Pinsoft-WeatherApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13' build

    - name: Run tests
      run: xcodebuild test -workspace Pinsoft-WeatherApp.xcworkspace -scheme Pinsoft-WeatherApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13'

