# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14.5

    steps:
    - uses: actions/checkout@v3

    - name: Xcode Setup
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4'

    - name: Build
      run: |
        xcodebuild build -workspace Pinsoft-WeatherApp.xcworkspace -scheme Pinsoft-WeatherApp clean build -sdk iphoneos CODE_SIGNING_ALLOWED=No

    - name: Run tests
      run: |
        xcodebuild test -workspace Pinsoft-WeatherApp.xcworkspace -scheme Pinsoft-WeatherApp clean build -sdk iphonesimulator -destination "platform=iOS Simulator,OS=17.5,name=iPhone 15 Pro" CODE_SIGNING_ALLOWED=No

